
name: Cross-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64 # Currently, GitHub Actions does not have arm64 for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.arch_target }}
          components: rustfmt

      # Install dependencies for cross-compiling (Linux and macOS)
      - name: Install cross-compilation dependencies (Linux and macOS only)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          sudo apt-get update || true
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get install gcc-aarch64-linux-gnu -y
          fi

      - name: Install arm64 Rust target
        if: matrix.arch == 'arm64'
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Build with Cargo
        run: cargo build --target ${{ matrix.arch_target }}

      # Run tests (optional)
      - name: Run tests
        run: cargo test --target ${{ matrix.arch_target }}

    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: '-C target-cpu=native'

